version: 2.1

jobs:
  lint-app:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout

  build-docker:
    docker:
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Node.js and build Docker containers
          command: |
            # Install Node.js
            apk add --no-cache nodejs npm

            docker build -t udagram-reverseproxy ./udagram-reverseproxy
            docker tag udagram-reverseproxy binhlh/udagram-reverseproxy:v1

            docker build -t udagram-api-feed ./udagram-api-feed
            docker tag udagram-api-feed binhlh/udagram-api-feed:v1

            docker build -t udagram-api-user ./udagram-api-user
            docker tag udagram-api-user binhlh/udagram-api-user:v1

            docker build -t udagram-frontend ./udagram-frontend
            docker tag udagram-frontend binhlh/udagram-frontend:v1

            echo "$DOCKERPW" | docker login -u binhlh --password-stdin
            docker push binhlh/udagram-api-feed:v1
            docker push binhlh/udagram-api-user:v1
            docker push binhlh/udagram-frontend:v1
            docker push binhlh/udagram-reverseproxy:v1

workflows:
  default:
    jobs:
      - lint-app
      - build-docker:
          requires: [lint-app]
